# Use postgres/example user/password credentials
version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=ibo
      - RABBITMQ_DEFAULT_PASS=12345